name: .NET

on:
  push:
    branches: ["main", "develop"]
  pull_request:
    branches: ["main", "develop"]

jobs:
  build:
    name: test dotnet
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
          cache-dependency-path: "./Thea/ClientApp/package-lock.json"
      - name: Npm install
        working-directory: ./Thea/ClientApp
        run: npm ci
      - run: npm run build --if-present
        name: Npm build
        working-directory: ./Thea/ClientApp
      - run: npm test
        name: Npm test
        working-directory: ./Thea/ClientApp
